version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: hdfs-namenode
    ports:
      - 9870:9870
      - 9001:9001
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: hdfs-datanode
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: yarn-resourcemanager
    environment:
      SERVICE_PRECONDITION: "namenode:9001 namenode:9870 datanode:9864"
    volumes:
      - ./yarn-resource-configuration/yarn-site.xml:/opt/hadoop-3.2.1/etc/hadoop/yarn-site.xml
      - ./yarn-resource-configuration/capacity-scheduler.xml:/opt/hadoop-3.2.1/etc/hadoop/capacity-scheduler.xml
      - ./yarn-resource-configuration/fair-scheduler.xml:/opt/hadoop-3.2.1/etc/hadoop/fair-scheduler.xml
    env_file:
      - ./hadoop.env
  nodemanager1:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: yarn-nodemanager
    environment:
      SERVICE_PRECONDITION: "namenode:9001 namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    container_name: mapReduce-historyserver
    environment:
      SERVICE_PRECONDITION: "namenode:9001 namenode:9870 datanode:9864 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    volumes:
      - ./hive-files:/opt/files
    env_file:
      - ./hadoop.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"
  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    env_file:
      - ./hadoop.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:9001 datanode:9864 hive-metastore-postgresql:5432"
    ports:
      - "9083:9083"
  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0
    container_name: hive-metastore-postgresql
  zookeeper:
    image: 'bitnami/zookeeper:3'
    ports:
     - '2181:2181'
    volumes:
     - 'zookeeper_data:/bitnami'
    environment:
     - ALLOW_ANONYMOUS_LOGIN=yes
  nifi:
    image: apache/nifi:latest
    ports:
     - 8080 # Unsecured HTTP Web Port
    volumes:
     - 'apache-nifi_data:/apache/nifi'
     - ./nifi:/opt/nifi_conf
    environment:
     - NIFI_WEB_HTTP_PORT=8080
     - NIFI_CLUSTER_IS_NODE=true
     - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
     - NIFI_ZK_CONNECT_STRING=zookeeper:2181
     - NIFI_ELECTION_MAX_WAIT=1 min
     - NIFI_SENSITIVE_PROPS_KEY=victoralfonsopratodeleon
    depends_on:
     - zookeeper
  superset:    
    build:
      context: superset
volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
  zookeeper_data:
  apache-nifi_data:
  nifi_data:
  superset_data:
